[shell.files]
"git/config" = "~/.gitconfig"
joshuto = ""  # TODO: consider yazi first
lazygit = { target = "~/.config/lazygit", type="symbolic" }
"starship/starship.toml" = { target = "~/.config/starship.toml", type="symbolic" }
python = ""
"ideavim/ideavimrc" = { target = "~/.ideavimrc", type="symbolic" }

tmux = "" # replaced by zellij
zellij = "~/.config/zellij" # TODO: Try zellij on windows
fastfetch = "~/.config/fastfetch"

[obsidian.files]
"vim/vimrc" = { target = "~/.obsidian.vimrc", type="symbolic" }

[vscode.files]
"vscode/settings.json" = "~/.vscode/settings.json"
"vscode/keybindings.json" = "~/.vscode/settings.json"

[shell.variables]
user_color = "7"
logo_file = "alogo.txt"

[nvim.files]
nvim = "~/.config/nvim"
