[shell.files]
"shell/bash" = { target = "~/.config/shell/bash", type = "symbolic"}
"shell/zsh" = { target = "~/.config/shell/zsh", type = "symbolic"}
"shell/common" = { target = "~/.config/shell/commmon", type = "symbolic"}

lazygit = { target = "~/.config/lazygit", type="symbolic" }
"starship/starship.toml" = { target = "~/.config/starship.toml", type="symbolic" }

zellij = "~/.config/zellij"
fastfetch = "~/.config/fastfetch"

[git.files]
"git/config" = "~/.gitconfig"
"git/gitignore" = { target = "~/.config/git/gitignore", type = "symbolic"}

[vim.files]
"vim/ideavimrc" = { target = "~/.ideavimrc", type = "symbolic" }
"vim/shared.vim" = { target = "~/.vim/shared.vim", type = "symbolic" }
"vim/obsidian.vimrc" = { target = "~/omnia/.obsidian.vimrc", type = "symbolic" }

[vscode.files]
"vscode/settings.json" = "~/.vscode/settings.json"
"vscode/keybindings.json" = "~/.vscode/keybindings.json"

[shell.variables]
user_color = "7"
logo_file = "alogo.txt"

[nvim.files]
nvim = { target = "~/.config/nvim", type = "symbolic" }
