[shell.files]
lazygit = { target = "~/AppData/Local/lazygit", type="symbolic" }
glazewm = { target = "~/.glzr/glazewm", type="symbolic" }
yasb = { target = "~/.config/yasb", type="symbolic" }
cava = { target="~/.config/cava", type="symbolic" }
"windows_terminal/settings.json" = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"

[powershell.files]
"powershell/profile.ps1" = { target = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1", type="symbolic" }

[vim.files]
"vim/ideavimrc" = { target = "~/.ideavimrc", type = "symbolic" }
"vim/shared.vim" = { target = "~/.vim/shared.vim", type = "symbolic" }
"vim/obsidian.vimrc" = { target = "~/omnia/.obsidian.vimrc", type = "symbolic" }

[vscode.files]
"vscode/settings.json" = { target="~/AppData/Roaming/Code/User/settings.json", type="symbolic" }
"vscode/keybindings.json" = { target="~/AppData/Roaming/Code/User/keybindings.json", type="symbolic" }

[nvim.files]
nvim = { target = "~/AppData/Local/nvim", type="symbolic" }

[wsl.files]
"wsl/wslconfig" = { target = "~/.wslconfig", type="symbolic" }

[yazi.files]
yazi = { target = "~/AppData/Roaming/yazi/config", type="symbolic" }
